<MyLayout>
    orientation: 'vertical'
    size: root.width, root.height

    AndroidCamera:
        index: 0
        resolution: self.camera_resolution
        allow_stretch: True
        play: True
        canvas.before:
            PushMatrix
            Rotate:
                angle: -90
                origin: self.center
            Scale:
                x: 1.333
                y: -1.333
                origin: self.center
        canvas.after:
            PopMatrix